image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      bin/setup
      bundler install && psql -c "create role ubuntu with createdb login password '${GITPOD_DB_PASSWORD:-changeme}';" && yarn install --check-files && rake db:setup && rails db:migrate && rails db:seed
    command: bin/rails server
